### PR TITLE
API 11951 Emit Encounter R4 Immunization

### PR DESCRIPTION
**Pull request by agarcia-va**

### CODE REVIEW

**Comment by taylorrassmannlibertyits** [comment]
You should probably add an Encounter example to `ImmunizationSamples`

**Comment by agarcia-va** [comment]
> You should probably add an Encounter example to `ImmunizationSamples`

Yes, I realized I missed that shortly after pushing opening this 😅  It will be pushed shortly!

**Review by taylorrassmannlibertyits — APPROVED** [review]
:shipit:

**Review by jblefkove-va — APPROVED** [review]
:shipit:

**Pull request merged**
