### PR TITLE
Api 1237 revoke manage endpoint

### PR DESCRIPTION
**Pull request by crolarlibertyva**
Requires https://github.com/department-of-veterans-affairs/health-apis-data-query-deployment/pull/79

### CODE REVIEW

**Comment by bschofield-va** [comment]
# DO NOT MERGE 
Until @beaugrantham-va gives indicates the new endpoints are available in lab and production.

**Comment by beaugrantham-va** [comment]
> # DO NOT MERGE
> 
> Until @beaugrantham-va gives indicates the new endpoints are available in lab and production.

ETA ~noon tomorrow.

**Comment by beaugrantham-va** [comment]
> > # DO NOT MERGE
> > Until @beaugrantham-va gives indicates the new endpoints are available in lab and production.
> 
> ETA ~noon tomorrow.

These endpoints are now live.

**Comment by bschofield-va** [comment]
I will merge this shortly

**Pull request merged**
